### model
model_name_or_path: path/to/your/model
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

flash_attn: fa2
### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_target: all

### dataset
dataset: sft_example  # video: mllm_video_demo
template: qwen2_vl
cutoff_len: 4096
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 64
dataloader_num_workers: 16

### output
output_dir: saves/qwen2_5vl-7b/lora/sft_example
logging_steps: 50
save_steps: 1500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
# batch_size per update step = per_device_train_batch_size * gradient_accumulation_steps * n_gpu
per_device_train_batch_size: 10
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
